MeetMe/MeetMe.Web/ViewModels/Search/SearchUserViewModel.cs
using AutoMapper;
using MeetMe.Data.Models;
using MeetMe.Web.ViewModels.Contracts;

namespace MeetMe.Web.ViewModels.Search
{
    public class SearchUserViewModel : ICustomMappings
    {
        public int Id { get; set; }

        public string FullName { get; set; }

        public string ImageUrl { get; set; }

        public bool IsFriend { get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<CustomUser, SearchUserViewModel>()
                     .ForMember(dest => dest.FullName, opts => opts.MapFrom(src => $"{src.FirstName} {src.LastName}"));
        }
    }
}

MeetMe/MeetMe.Web/ViewModels/Search/SearchViewModel.cs
using System.Collections.Generic;

namespace MeetMe.Web.ViewModels.Search
{
    public class SearchViewModel
    {
        public IEnumerable<SearchUserViewModel> FoundUsers { get; set; }

        public int ResultsCount { get; set; }

        public string SearchedPattern { get; set; }
    }
}

MeetMe/MeetMe.Web/Controllers/ProfileController.cs
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;
using MeetMe.Web.Models.Profile;

namespace MeetMe.Web.Controllers
{
    public class ProfileController : Controller
    {
        private const string UpdatePersonalInformationError = "Something went wrong, please try again";
        private const string UpdatePersonalInformationSuccess = "Successfully updated personal info";

        private readonly IAccountService accountService;
        private readonly IUserService userService;
        private readonly IFriendService friendService;
        private readonly IViewModelService viewModelService;

        public ProfileController(
            IAccountService accountService,
            IUserService userService,
            IFriendService friendService,
            IViewModelService viewModelService)
        {
            Guard.WhenArgument(accountService, "AccountService").IsNull().Throw();
            Guard.WhenArgument(userService, "UserService").IsNull().Throw();
            Guard.WhenArgument(friendService, "FriendService").IsNull().Throw();
            Guard.WhenArgument(viewModelService, "ViewModelService").IsNull().Throw();

            this.accountService = accountService;
            this.userService = userService;
            this.friendService = friendService;
            this.viewModelService = viewModelService;
        }

        [HttpGet]
        public ActionResult Index(int id)
        {
            var user = this.userService.GetById(id);
            var friends = this.friendService.GetAllUserFriends(user.Id);
            var model = this.viewModelService.GetMappedProfile(user);
            var mappedFriends = this.viewModelService.GetMappedUserFriends(friends);
            model.Friends = mappedFriends;

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProfilePersonalnfo model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PartialView("_ProfilePersonalInfoPartial", model);
            }

            var updatedUser = this.accountService.EditProfile(model);
            var updatedModel = this.viewModelService.GetMappedProfilePersonalInfo(updatedUser);
            return this.PartialView("_ProfilePersonalInfoPartial", updatedModel);
        }

        [HttpPost]
        public ActionResult ChangeProfileImage(int id)
        {
            string result = string.Empty;

            foreach (string file in Request.Files)
            {
                var fileContent = Request.Files[file];
                if (fileContent.ContentType == "image/jpeg" || fileContent.ContentType == "image/png")
                {
                    if (fileContent.ContentLength < 1000000)
                    {
                        this.accountService.ChangeProfileImage(fileContent.InputStream, id);
                        result = "Profile image successfully changed.Please, refresh";
                    }
                    else
                    {
                        result = "This image is too big";
                    }
                }
                else
                {
                    result = "Invalid content type, please add image";
                }
            }

            return this.Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemoveFriend(int id, string userId)
        {
            var user = this.userService.GetByIndentityId(userId);
            this.friendService.RemoveFriend(user.Id, id);

            var friends = this.friendService.GetAllUserFriends(user.Id);
            var model = this.viewModelService.GetMappedProfile(user);
            var mappedFriends = this.viewModelService.GetMappedUserFriends(friends);
            model.Friends = mappedFriends;

            return this.PartialView("_ProfileFriendsPartial", model);
        }
    }
}

MeetMe/MeetMe.Web/Controllers/SearchController.cs
using System.Linq;
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;
using MeetMe.Web.Helpers.Contracts;
using MeetMe.Web.Models.Search;

namespace MeetMe.Web.Controllers
{
    public class SearchController : Controller
    {
        private const int DefaultUsersSkip = 0;
        private const int DefaultUsersToShow = 5;

        private readonly ISearchService searchService;
        private readonly IViewModelService viewModelService;
        private readonly IIdentityHelper identityHelper;

        public SearchController(
            ISearchService searchService,
            IViewModelService viewModelService,
            IIdentityHelper identityHelper)
        {
            Guard.WhenArgument(searchService, "SearchService").IsNull().Throw();
            Guard.WhenArgument(viewModelService, "ViewModelService").IsNull().Throw();
            Guard.WhenArgument(identityHelper, "IdentityHelper").IsNull().Throw();

            this.searchService = searchService;
            this.viewModelService = viewModelService;
            this.identityHelper = identityHelper;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userId = this.identityHelper.GetCurrentUserId();
            if (userId == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var results = this.searchService.SearchedUsers(string.Empty, DefaultUsersSkip, DefaultUsersToShow);
            var mappedUsers = this.viewModelService.GetMappedSearchedUsers(results, userId);
            var model = new SearchViewModel();
            model.SearchedPattern = string.Empty;
            model.ResultsCount = results.Count();
            model.FoundUsers = mappedUsers;

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string pattern, int skip, int count, string userId)
        {
            var results = this.searchService.SearchedUsers(pattern, skip, count);
            var mappedUsers = this.viewModelService.GetMappedSearchedUsers(results, userId);
            var model = new SearchViewModel();
            model.SearchedPattern = pattern;
            model.ResultsCount = results.Count();
            model.FoundUsers = mappedUsers;

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowMoreResults(string pattern, int skip, int count, string userId)
        {
            if (pattern == null)
            {
                pattern = string.Empty;
            }

            var results = this.searchService.SearchedUsers(pattern, skip, count);
            var model = this.viewModelService.GetMappedSearchedUsers(results, userId);

            return this.PartialView("_SearchResultsPartial", model);
        }
    }
}

MeetMe/MeetMe.Web/Views/Search/Index.cshtml
@using MeetMe.Web.Models.Search
@model SearchViewModel

@section styles {
    <link href="~/Content/search.css" rel="stylesheet" />
}
<div id="search">
    <hgroup>
        <h1>Search Results</h1>
        <h2 class="lead"><strong class="text-danger">@Model.ResultsCount</strong> results were found for the search for "<strong class="text-danger">@Model.SearchedPattern</strong>"</h2>
    </hgroup>
    <ul class="search-list" id="all-results">
        @Html.Partial("_SearchResultsPartial", Model.FoundUsers)
    </ul>
    @if (Model.ResultsCount > 5)
    {
        using (Ajax.BeginForm("ShowMoreResults", "Search", new { pattern = Model.SearchedPattern, skip = 5, count = byte.MaxValue, userId = User.Identity.GetUserId() }, new AjaxOptions()
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.InsertAfter,
            UpdateTargetId = "all-results",
            OnSuccess = "hideShowMoreLink"
        }, new { id = "showMoreResults" }))
        {
            @Html.AntiForgeryToken()
            <h4 class="text-center">
                <input type="submit" class="btn btn-block" value="Show more" />
            </h4>
        }
    }
</div>

@section scripts {
    @Scripts.Render("~/Scripts/search.js")
}

MeetMe/MeetMe.Web/Views/Search/_SearchResultsPartial.cshtml
@using MeetMe.Web.Models.Search
@model IEnumerable<SearchUserViewModel>

@foreach (var user in Model)
{
    <li class="search-item">
        <a class="search-section" href="@Url.Action("Index", "Profile", new { id = user.Id })">
            <img src="@user.ImageUrl" width="100" height="100">
            <span class="username-color">@user.FullName</span>
        </a>
        @if (User.Identity.IsAuthenticated && User.Identity.GetUserId() != user.AspIdentityUserId)
        {
            if (user.IsFriend)
            {
                <span class="btn btn-info pull-right">Friends</span>
            }
            else
            {
                <button id="btn-friend-@user.Id" data-id="@user.Id" current-id="@User.Identity.GetUserId()" class="btn btn-primary pull-right add-friend" type="submit"><i class="glyphicon glyphicon-plus"></i> Add friend</button>
            }
        }
        <hr />
    </li>
}