MeetMe/MeetMe.Web/Controllers/NavigationController.cs
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;
using MeetMe.Web.Models.Navigation;

namespace MeetMe.Web.Controllers
{
    public class NavigationController : Controller
    {
        private readonly IStatisticService statisticService;
        private readonly IMapperService mapperService;

        public NavigationController(
            IStatisticService statisticService,
            IMapperService mapperService)
        {
            Guard.WhenArgument(statisticService, "StatisticService").IsNull().Throw();
            Guard.WhenArgument(mapperService, "MapperService").IsNull().Throw();

            this.statisticService = statisticService;
            this.mapperService = mapperService;
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [Authorize]
        public ActionResult Index(string id)
        {
            var statistic = this.statisticService.GetUserStatistic(id);
            var model = this.mapperService.MapObject<StatisticViewModel>(statistic);

            return this.PartialView("_IndexPartial", model);
        }
    }
}

MeetMe/MeetMe.Web/Controllers/SearchController.cs
using System.Linq;
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;
using MeetMe.Web.Helpers.Contracts;
using MeetMe.Web.Models.Search;

namespace MeetMe.Web.Controllers
{
    public class SearchController : Controller
    {
        private const int DefaultUsersSkip = 0;
        private const int DefaultUsersToShow = 5;

        private readonly ISearchService searchService;
        private readonly IViewModelService viewModelService;
        private readonly IIdentityHelper identityHelper;

        public SearchController(
            ISearchService searchService,
            IViewModelService viewModelService,
            IIdentityHelper identityHelper)
        {
            Guard.WhenArgument(searchService, "SearchService").IsNull().Throw();
            Guard.WhenArgument(viewModelService, "ViewModelService").IsNull().Throw();
            Guard.WhenArgument(identityHelper, "IdentityHelper").IsNull().Throw();

            this.searchService = searchService;
            this.viewModelService = viewModelService;
            this.identityHelper = identityHelper;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userId = this.identityHelper.GetCurrentUserId();
            if (userId == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var results = this.searchService.SearchedUsers(string.Empty, DefaultUsersSkip, DefaultUsersToShow);
            var mappedUsers = this.viewModelService.GetMappedSearchedUsers(results, userId);
            var model = new SearchViewModel();
            model.SearchedPattern = string.Empty;
            model.ResultsCount = results.Count();
            model.FoundUsers = mappedUsers;

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string pattern, int skip, int count, string userId)
        {
            var results = this.searchService.SearchedUsers(pattern, skip, count);
            var mappedUsers = this.viewModelService.GetMappedSearchedUsers(results, userId);
            var model = new SearchViewModel();
            model.SearchedPattern = pattern;
            model.ResultsCount = results.Count();
            model.FoundUsers = mappedUsers;

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowMoreResults(string pattern, int skip, int count, string userId)
        {
            if (pattern == null)
            {
                pattern = string.Empty;
            }

            var results = this.searchService.SearchedUsers(pattern, skip, count);
            var model = this.viewModelService.GetMappedSearchedUsers(results, userId);

            return this.PartialView("_SearchResultsPartial", model);
        }
    }
}

MeetMe/MeetMe.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MeetMe</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (!this.Request.IsAuthenticated)
                {
                    @Html.ActionLink("MeetMe", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                @if (!this.Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                    </ul>
                    <div class="navbar-form navbar-right" role="search">
                        @using (Html.BeginForm("Index", "Search", FormMethod.Post, new { @class = "custom-autocomplete" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <input type="text" id="search-bar" name="pattern" class="form-control" placeholder="Search">
                                <input type="hidden" name="skip" value="0" />
                                <input type="hidden" name="count" value="5" />
                                <input type="hidden" name="userId" value="@User.Identity.GetUserId()" />
                            </div>
                            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                        }
                    </div>
                }
                else
                {
                    @Html.Action("Index", "Navigation", new { id = User.Identity.GetUserId() })
                    <div class="navbar-form navbar-right" role="search">
                        @using (Html.BeginForm("Index", "Search", FormMethod.Post, new { @class = "custom-autocomplete" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <input type="text" id="search-bar" name="pattern" class="form-control" placeholder="Search">
                                <input type="hidden" name="skip" value="0" />
                                <input type="hidden" name="count" value="5" />
                                <input type="hidden" name="userId" value="@User.Identity.GetUserId()" />
                            </div>
                            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                        }
                        <div class="form-group" id="profile-partial-page">
                            @Html.Action("ProfilePartial", "Home")
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center panel-footer">
            <div class="pull-right">
                <a href="https://github.com/Warez-VD/MeetMe" class="special github fa fa-lg fa-github pull-right spacing-right">
                </a>
                <a href="#" class="special fa fa-youtube text-danger">
                </a>
            </div>
            <div>
                <h4>&copy; League of the one</h4>
                <p class="text-center">Telerik Academy 2017</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunobtrusive")
    @Scripts.Render("~/Scripts/jquery.signalR-2.2.1.js")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("~/Scripts/requester.js")
    @Scripts.Render("~/Scripts/autocomplete.js")
    @Scripts.Render("~/Scripts/navigation.js")
    @RenderSection("scripts", required: false)
</body>
</html>