MeetMe/MeetMe.Web/ViewModels/Home/HomeViewModel.cs
namespace MeetMe.Web.ViewModels.Home
{
    public class HomeViewModel
    {
        public LoginViewModel Login { get; set; }

        public RegisterViewModel Register { get; set; }

        public PersonalInfoViewModel PersonalInfo { get; set; }
    }
}

MeetMe/MeetMe.Web/ViewModels/Home/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MeetMe.Web.ViewModels.Home
{
    public class LoginViewModel
    {
        public int ShowServerError { get; set; }

        [Required(ErrorMessage = "Please enter email")]
        [RegularExpression("[a-zA-Z][a-zA-Z0-9\\-\\.]*[a-zA-Z]@[a-zA-Z][a-zA-Z0-9\\-\\.]+[a-zA-Z]+\\.[a-zA-Z]{2,4}", ErrorMessage = "Please, enter valid email")]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter password")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

MeetMe/MeetMe.Web/ViewModels/Home/PersonalInfoViewModel.cs
using MeetMe.Data.Models;
using MeetMe.Web.ViewModels.Contracts;

namespace MeetMe.Web.ViewModels.Home
{
    public class PersonalInfoViewModel : IMapFrom<CustomUser>
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string ProfileImageUrl { get; set; }

        public int Age { get; set; }

        public string City { get; set; }

        public string School { get; set; }

        public string Company { get; set; }
    }
}

MeetMe/MeetMe.Web/ViewModels/Home/ProfilePartialViewModel.cs
using MeetMe.Data.Models;
using MeetMe.Web.ViewModels.Contracts;

namespace MeetMe.Web.ViewModels.Home
{
    public class ProfilePartialViewModel : IMapFrom<CustomUser>
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string ProfileImageUrl { get; set; }
    }
}

MeetMe/MeetMe.Web/ViewModels/Home/PublicationViewModel.cs
using MeetMe.Data.Models;
using MeetMe.Web.ViewModels.Contracts;
using System;
using System.Collections.Generic;
using AutoMapper;

namespace MeetMe.Web.ViewModels.Home
{
    public class PublicationViewModel : ICustomMappings
    {
        public int Id { get; set; }

        public string Content { get; set; }
        
        public string Author { get; set; }

        public string AuthorImageUrl { get; set; }

        public DateTime CreatedOn { get; set; }

        public int Likes { get; set; }

        public int Dislikes { get; set; }

        public IEnumerable<Comment> Comments { get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Publication, PublicationViewModel>()
                    .ForMember(dest => dest.Author, opts => opts.MapFrom(src => $"{src.Author.FirstName} {src.Author.LastName}"));
        }
    }
}

MeetMe/MeetMe.Web/Controllers/HomeController.cs
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;
using MeetMe.Web.Auth.Contracts;
using MeetMe.Web.Helpers.Contracts;
using MeetMe.Web.Models.Home;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace MeetMe.Web.Controllers
{
    public class HomeController : Controller
    {
        private const string DefaultProfileLogoPath = "~/Content/default-user.jpg";

        private readonly IAccountService accountService;
        private readonly IUserService userService;
        private readonly IStatisticService statisticService;
        private readonly IViewModelService viewModelService;
        private readonly ISignInManager signInManager;
        private readonly IUserManager userManager;
        private readonly IIdentityHelper identityHelper;

        public HomeController(
            IAccountService accountService,
            IUserService userService,
            IStatisticService statisticService,
            IViewModelService viewModelService,
            ISignInManager signInManager,
            IUserManager userManager,
            IIdentityHelper identityHelper)
        {
            Guard.WhenArgument(accountService, "AccountService").IsNull().Throw();
            Guard.WhenArgument(userService, "UserService").IsNull().Throw();
            Guard.WhenArgument(statisticService, "StatisticService").IsNull().Throw();
            Guard.WhenArgument(viewModelService, "ViewModelService").IsNull().Throw();
            Guard.WhenArgument(signInManager, "SignInManager").IsNull().Throw();
            Guard.WhenArgument(userManager, "UserManager").IsNull().Throw();
            Guard.WhenArgument(identityHelper, "IdentityHelper").IsNull().Throw();

            this.accountService = accountService;
            this.userService = userService;
            this.statisticService = statisticService;
            this.viewModelService = viewModelService;
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.identityHelper = identityHelper;
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return this.HttpContext.GetOwinContext().Authentication;
            }
        }

        [HttpGet]
        public ActionResult Index()
        {
            HomeViewModel model = new HomeViewModel();
            if (this.Request.IsAuthenticated)
            {
                string userId = this.identityHelper.GetCurrentUserId();
                var user = this.userService.GetByIndentityId(userId);
                model.PersonalInfo = this.viewModelService.GetMappedPersonalInfo(user);
            }

            return this.View(model);
        }

        [HttpGet]
        public ActionResult About()
        {
            return this.View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(HomeViewModel model, string returnUrl)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View("Index", model);
            }

            var result = await this.signInManager.PasswordSignInAsync(model.Login.Email, model.Login.Password, true, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return this.RedirectToLocal(returnUrl);
                case SignInStatus.Failure:
                default:
                    this.ModelState.AddModelError("Login.ShowServerError", "Invalid username or password");
                    return this.View("Index", model);
            }
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(HomeViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var user = this.accountService.CreateUser(model.Register.Email, model.Register.Email);
                var result = await this.userManager.CreateAsync(user, model.Register.Password);
                if (result.Succeeded)
                {
                    string profileLogoFullPath = this.Server.MapPath(DefaultProfileLogoPath);
                    this.accountService.Register(model.Register.FirstName, model.Register.LastName, user.Id, profileLogoFullPath);
                    this.statisticService.CreateStatistic(user.Id);
                    await this.signInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                    return this.RedirectToAction("Index", "Home");
                }

                this.ModelState.AddModelError("Register.ShowServerError", "User with this email already exists");
            }

            return this.View("Index", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            this.AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return this.RedirectToAction("Index", "Home");
        }

        [ChildActionOnly]
        public ActionResult ProfilePartial()
        {
            string id = this.identityHelper.GetCurrentUserId();
            var user = this.userService.GetByIndentityId(id);
            var model = this.viewModelService.GetMappedProfilePartial(user);

            return this.PartialView("_ProfilePartial", model);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (this.Url.IsLocalUrl(returnUrl))
            {
                return this.Redirect(returnUrl);
            }

            return this.RedirectToAction("Index", "Home");
        }
    }
}

MeetMe/MeetMe.Web/Controllers/ProfileController.cs
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;
using MeetMe.Web.Models.Profile;

namespace MeetMe.Web.Controllers
{
    public class ProfileController : Controller
    {
        private const string UpdatePersonalInformationError = "Something went wrong, please try again";
        private const string UpdatePersonalInformationSuccess = "Successfully updated personal info";

        private readonly IAccountService accountService;
        private readonly IUserService userService;
        private readonly IFriendService friendService;
        private readonly IViewModelService viewModelService;

        public ProfileController(
            IAccountService accountService,
            IUserService userService,
            IFriendService friendService,
            IViewModelService viewModelService)
        {
            Guard.WhenArgument(accountService, "AccountService").IsNull().Throw();
            Guard.WhenArgument(userService, "UserService").IsNull().Throw();
            Guard.WhenArgument(friendService, "FriendService").IsNull().Throw();
            Guard.WhenArgument(viewModelService, "ViewModelService").IsNull().Throw();

            this.accountService = accountService;
            this.userService = userService;
            this.friendService = friendService;
            this.viewModelService = viewModelService;
        }

        [HttpGet]
        public ActionResult Index(int id)
        {
            var user = this.userService.GetById(id);
            var friends = this.friendService.GetAllUserFriends(user.Id);
            var model = this.viewModelService.GetMappedProfile(user);
            var mappedFriends = this.viewModelService.GetMappedUserFriends(friends);
            model.Friends = mappedFriends;

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProfilePersonalnfo model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PartialView("_ProfilePersonalInfoPartial", model);
            }

            var updatedUser = this.accountService.EditProfile(model);
            var updatedModel = this.viewModelService.GetMappedProfilePersonalInfo(updatedUser);
            return this.PartialView("_ProfilePersonalInfoPartial", updatedModel);
        }

        [HttpPost]
        public ActionResult ChangeProfileImage(int id)
        {
            string result = string.Empty;

            foreach (string file in Request.Files)
            {
                var fileContent = Request.Files[file];
                if (fileContent.ContentType == "image/jpeg" || fileContent.ContentType == "image/png")
                {
                    if (fileContent.ContentLength < 1000000)
                    {
                        this.accountService.ChangeProfileImage(fileContent.InputStream, id);
                        result = "Profile image successfully changed.Please, refresh";
                    }
                    else
                    {
                        result = "This image is too big";
                    }
                }
                else
                {
                    result = "Invalid content type, please add image";
                }
            }

            return this.Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemoveFriend(int id, string userId)
        {
            var user = this.userService.GetByIndentityId(userId);
            this.friendService.RemoveFriend(user.Id, id);

            var friends = this.friendService.GetAllUserFriends(user.Id);
            var model = this.viewModelService.GetMappedProfile(user);
            var mappedFriends = this.viewModelService.GetMappedUserFriends(friends);
            model.Friends = mappedFriends;

            return this.PartialView("_ProfileFriendsPartial", model);
        }
    }
}

MeetMe/MeetMe.Web/Controllers/PublicationController.cs
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;

namespace MeetMe.Web.Controllers
{
    public class PublicationController : Controller
    {
        private readonly byte[] emptyPublicationImage = new byte[0];
        private readonly IPublicationService publicationService;
        private readonly ITextService textService;
        private readonly IViewModelService viewModelService;

        public PublicationController(
            IPublicationService publicationService,
            ITextService textService,
            IViewModelService viewModelService)
        {
            Guard.WhenArgument(publicationService, "PublicationService").IsNull().Throw();
            Guard.WhenArgument(textService, "TextService").IsNull().Throw();
            Guard.WhenArgument(viewModelService, "ViewModelService").IsNull().Throw();

            this.publicationService = publicationService;
            this.textService = textService;
            this.viewModelService = viewModelService;
        }

        [Authorize]
        [HttpGet]
        public ActionResult Publications(string id, int skip, int count)
        {
            var publications = this.publicationService.FriendsPublications(id, skip, count);
            var model = this.viewModelService.GetMappedPublications(publications);

            return this.PartialView("_PublicationPartial", model);
        }
        
        [HttpGet]
        public ActionResult UserPublications(string id, int skip, int count)
        {
            var publications = this.publicationService.UserPublications(id, skip, count);
            var model = this.viewModelService.GetMappedPublications(publications);

            return this.PartialView("_PublicationPartial", model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPublication(string content, string userId, string imageBase64, int skip, int count)
        {
            if (imageBase64 != string.Empty)
            {
                var base64 = this.textService.ConvertBase64(imageBase64);
                this.publicationService.CreatePublication(content, userId, base64);
            }
            else
            {
                this.publicationService.CreatePublication(content, userId, this.emptyPublicationImage);
            }

            var publications = this.publicationService.FriendsPublications(userId, skip, count);
            var model = this.viewModelService.GetMappedPublications(publications);

            return this.PartialView("_PublicationPartial", model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPersonalPublication(string content, string userId, string imageBase64, int skip, int count)
        {
            if (imageBase64 != string.Empty)
            {
                var base64 = this.textService.ConvertBase64(imageBase64);
                this.publicationService.CreatePublication(content, userId, base64);
            }
            else
            {
                this.publicationService.CreatePublication(content, userId, this.emptyPublicationImage);
            }

            var publications = this.publicationService.UserPublications(userId, skip, count);
            var model = this.viewModelService.GetMappedPublications(publications);

            return this.PartialView("_PublicationPartial", model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(int id, string comment, string userId)
        {
            this.publicationService.CreatePublicationComment(id, comment, userId);

            var publication = this.publicationService.GetById(id);
            var model = this.viewModelService.GetMappedComments(publication);

            return this.PartialView("_PublicationCommentPartial", model);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Comments(int id)
        {
            var publication = this.publicationService.GetById(id);
            var model = this.viewModelService.GetMappedComments(publication);

            return this.PartialView("_PublicationCommentPartial", model);
        }
    }
}

MeetMe/MeetMe.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h3>About page</h3>

MeetMe/MeetMe.Web/Views/Home/Index.cshtml
@using MeetMe.Web.Models.Home
@model HomeViewModel

@section styles {
    <link href="~/Content/home.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/publication.css" rel="stylesheet" />
}

@if (this.Request.IsAuthenticated)
{
    <div id="wrapper" class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="row profile">
                    <div class="profile-sidebar">
                        <div class="profile-userpic">
                            <img src=@Model.PersonalInfo.ProfileImageUrl class="img-responsive"
                                 alt="User profile image">
                        </div>
                        <div class="profile-usertitle">
                            <div class="profile-usertitle-name">
                                @Model.PersonalInfo.FirstName @Model.PersonalInfo.LastName
                            </div>
                        </div>
                        <div class="profile-usermenu">
                            <ul class="nav">
                                @if (Model.PersonalInfo.Company != null)
                                {
                                    <li>
                                        <span>
                                            <i class="fa fa-briefcase"></i> Work for @Model.PersonalInfo.Company
                                        </span>
                                    </li>
                                }
                                @if (Model.PersonalInfo.School != null)
                                {
                                    <li>
                                        <span>
                                            <i class="fa fa-graduation-cap"></i> Study at @Model.PersonalInfo.School
                                        </span>
                                    </li>
                                }
                                @if (Model.PersonalInfo.City != null)
                                {
                                    <li>
                                        <span>
                                            <i class="fa fa-map-marker"></i> From @Model.PersonalInfo.City
                                        </span>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default" id="publication-add">
                    <div class="panel-heading">
                        <h4>
                            <i id="image-add" title="Add publication image" class="fa fa-picture-o"></i>
                            <input id="publication-picture" title="Add publication image" type="file" name="file" />
                             New publication
                        </h4>
                    </div>
                    <div class="panel-body">
                        @using (Ajax.BeginForm("AddPublication", "Publication", new AjaxOptions()
                        {
                            UpdateTargetId = "publications",
                            InsertionMode = InsertionMode.Replace,
                            HttpMethod = "POST",
                            OnSuccess = "ajaxSuccess"
                        }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="input-group text-center">
                                <input class="form-control input-lg" placeholder="What are you thinking?" type="text" id="publication-content" name="content">
                                <input type="hidden" name="userId" id="user-id" value="@User.Identity.GetUserId()" />
                                <input type="hidden" id="image-base" name="imageBase64" />
                                <input type="hidden" id="username-addpublication" value="@Model.PersonalInfo.FirstName @Model.PersonalInfo.LastName" />
                                <input type="hidden" name="skip" value="0" />
                                <input type="hidden" name="count" value="20" />
                                <div class="input-group-btn"><input class="btn btn-lg btn-primary" type="submit" id="btn-publication" value="Publish" /></div>
                            </div>
                            <div>
                                <div id="add-publication-content"></div>
                            </div>
                        }
                    </div>
                </div>
                <div id="publications">
                    @Html.Action("Publications", "Publication", new { id = User.Identity.GetUserId(), skip = 0, count = 20 })
                </div>
                <div id="show-publications-user" class="text-center show-publications">
                    @Ajax.ActionLink("Show all publications", "Publications", "Publication", new { id = User.Identity.GetUserId(), skip = 20, count = byte.MaxValue }, new AjaxOptions
               {
                   HttpMethod = "GET",
                   InsertionMode = InsertionMode.InsertAfter,
                   UpdateTargetId = "publications",
                   OnSuccess = "showHidePublications"
               }, new { @class = "btn btn-info" })
                </div>
                <div id="hide-publications-user" class="text-center hidden hide-publications">
                    @Ajax.ActionLink("Hide publications", "Publications", "Publication", new { id = User.Identity.GetUserId(), skip = 0, count = 20 }, new AjaxOptions
               {
                   HttpMethod = "GET",
                   InsertionMode = InsertionMode.Replace,
                   UpdateTargetId = "publications",
                   OnSuccess = "showPublications"
               }, new { @class = "btn btn-info" })
                </div>
            </div>
            <div class="col-md-3">
                    <div class="card">
                        <div class="text-center">
                            <a href="#"><img src="~/Content/logo.png" class="img-circle" /></a>
                            <h3 class="text-center">MeetMe</h3>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="home">
                                <p>MeetMe gives you the chance to meet your friends and share what you think.</p>
                            </div>
                            <div class="tab-pane fade" id="about">
                                <p>MeetMe is a social network for meeting new people. MeetMe makes it easy to discover new people to chat with and share you new moments.</p>
                            </div>
                        </div>

                        <ul class="nav nav-tabs nav-tab nav-justified" id="myTab">
                            <li class="active"><a class="tab-btn" href="#home" data-toggle="tab">MeetMe</a></li>
                            <li><a class="tab-btn" href="#about" data-toggle="tab">About</a></li>
                        </ul>
                    </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="container">
        <div id="tabs-home" class="row slider" style="background:url(../../Content/home.jpg) no-repeat center fixed;">
            <div class="col-sm-3">
            </div>
            <div id="wea" class="col-sm-9">
                <div class="pull-right">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @using (Html.BeginForm("Login", "Home", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationMessageFor(m => m.Login.ShowServerError, string.Empty, new { @class = "text-danger" })
                                @Html.TextBoxFor(m => m.Login.Email, new { @class = "form-control", placeholder = "Email" })
                                @Html.ValidationMessageFor(m => m.Login.Email, string.Empty, new { @class = "text-danger" });
                                @Html.PasswordFor(m => m.Login.Password, new { @class = "form-control", placeholder = "Password" })
                                <input type="submit" value="Sign in" class="btn btn-primary" />
                            }
                        </div>
                    </div>
                </div>

                <div class="pull-right">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <p>New to MeetMe? Sign up</p>
                        </div>
                        <div class="panel-body">
                            @using (Html.BeginForm("Register", "Home", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationMessageFor(m => m.Register.ShowServerError, string.Empty, new { @class = "text-danger" })
                                @Html.TextBoxFor(m => m.Register.Email, new { @class = "form-control", placeholder = "Email" })
                                @Html.ValidationMessageFor(m => m.Register.Email, string.Empty, new { @class = "text-danger" })
                                @Html.PasswordFor(m => m.Register.Password, new { @class = "form-control", placeholder = "Password" })
                                @Html.ValidationMessageFor(m => m.Register.Password, string.Empty, new { @class = "text-danger" })
                                @Html.TextBoxFor(m => m.Register.FirstName, new { @class = "form-control", placeholder = "First name" })
                                @Html.ValidationMessageFor(m => m.Register.FirstName, string.Empty, new { @class = "text-danger" })
                                @Html.TextBoxFor(m => m.Register.LastName, new { @class = "form-control", placeholder = "Last name" })
                                @Html.ValidationMessageFor(m => m.Register.LastName, string.Empty, new { @class = "text-danger" })
                                <input type="submit" value="Sign up" class="btn btn-success" />
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts {
    @Scripts.Render("~/Scripts/notification.js")
    @Scripts.Render("~/Scripts/publication.js")
    @Scripts.Render("~/Scripts/publication-attach-image.js")
}

MeetMe/MeetMe.Web/Views/Home/_ProfilePartial.cshtml
@using MeetMe.Web.Models.Home
@model ProfilePartialViewModel
<div>
    <div class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="user-avatar pull-left" style="margin-right:8px; margin-top:-5px;">
                <img src="@Model.ProfileImageUrl" class="img-responsive img-circle" title="John Doe" alt="John Doe" width="30px" height="30px">
            </span>
            <span class="user-name">
                @Model.FirstName @Model.LastName
            </span>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li>
                <div class="navbar-content">
                    <div class="row">
                        <div class="col-md-5">
                            <img src="@Model.ProfileImageUrl" alt="Alternate Text" class="img-responsive" width="120px" height="120px" />
                        </div>
                        <div class="col-md-7">
                            <span>@Model.FirstName @Model.LastName</span>
                            <div class="divider">
                            </div>
                            <a href="@Url.Action("Index", "Profile", new { id = Model.Id })" class="btn btn-default btn-xs"><i class="fa fa-user-o" aria-hidden="true"></i> Profile</a>
                        </div>
                    </div>
                </div>
                <div class="navbar-footer">
                    <div class="navbar-footer-content">
                        <div class="row">
                            <div class="col-md-6">
                                <a href="#" class="btn btn-default btn-sm"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Change Passowrd</a>
                            </div>
                            <div class="col-md-6">
                                @using (Html.BeginForm("LogOff", "Home", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <a id="btn-signout" class="btn btn-default btn-sm pull-right" href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-power-off" aria-hidden="true"></i> Sign out</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>