MeetMe/MeetMe.Web/Controllers/NotificationController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Bytes2you.Validation;
using MeetMe.Services.Contracts;
using MeetMe.Web.Models.Notifications;

namespace MeetMe.Web.Controllers
{
    public class NotificationController : Controller
    {
        private const int DefaultNotificationsSkip = 0;
        private const int DefaultNotificationsTake = 20;

        private readonly INotificationService notificationService;
        private readonly IStatisticService statisticService;
        private readonly IUserService userService;
        private readonly IViewModelService viewModelService;

        public NotificationController(
            INotificationService notificationService,
            IStatisticService statisticService,
            IUserService userService,
            IViewModelService viewModelService)
        {
            Guard.WhenArgument(notificationService, "NotificationService").IsNull().Throw();
            Guard.WhenArgument(statisticService, "StatisticService").IsNull().Throw();
            Guard.WhenArgument(userService, "UserService").IsNull().Throw();
            Guard.WhenArgument(viewModelService, "ViewModelService").IsNull().Throw();

            this.notificationService = notificationService;
            this.statisticService = statisticService;
            this.userService = userService;
            this.viewModelService = viewModelService;
        }

        [HttpGet]
        public ActionResult Index(string id)
        {
            if (id == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var model = new NotificationViewModel();
            var notifications = this.notificationService.UserNotifications(DefaultNotificationsSkip, DefaultNotificationsTake, id);
            model.Notifications = this.viewModelService.GetMappedUserNotifications(notifications);

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowMoreResults(int skip, int count, string userId)
        {
            var notifications = this.notificationService.UserNotifications(skip, count, userId);
            var model = this.viewModelService.GetMappedUserNotifications(notifications);

            return this.PartialView("_NotificationsPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveNotification(int id, string userId)
        {
            this.notificationService.RemoveNotification(id);
            var notifications = this.notificationService.UserNotifications(DefaultNotificationsSkip, DefaultNotificationsTake, userId);
            var model = this.viewModelService.GetMappedUserNotifications(notifications);

            return this.PartialView("_NotificationsPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveAllNotifications(string id)
        {
            this.notificationService.RemoveAllNotifications(id);
            this.statisticService.MarkAsVisitedNotifications(id);
            var model = new List<NotificationUserViewModel>();

            return this.PartialView("_NotificationsPartial", model);
        }

        [HttpPost]
        public void MarkVisited(string id)
        {
            this.statisticService.MarkAsVisitedNotifications(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AcceptFriendship(string id, int authorId, int notificationId)
        {
            this.userService.AddFriend(id, authorId);
            this.notificationService.RemoveNotification(notificationId);
            var notifications = this.notificationService.UserNotifications(DefaultNotificationsSkip, DefaultNotificationsTake, id);
            var model = this.viewModelService.GetMappedUserNotifications(notifications);

            return this.PartialView("_NotificationsPartial", model);
        }
    }
}

MeetMe/MeetMe.Web/Views/Notification/Index.cshtml
@using Microsoft.AspNet.Identity
@using MeetMe.Web.Models.Notifications
@model NotificationViewModel

@section styles {
    <link href="~/Content/notification.css" rel="stylesheet" type="text/css" />
}

<div>
    <h1>Notifications</h1>
</div>
@if (Model.Notifications.Count() != 0)
{
    using (Ajax.BeginForm("RemoveAllNotifications", "Notification", new { id = User.Identity.GetUserId() }, new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "notifications-container",
        OnSuccess = "hideRemoveAllNotifications"
    }, new { @class = "format", id = "removeAllNotifications" }))
    {
        @Html.AntiForgeryToken()
        <button type="submit" class="pull-right btn btn-danger">Remove all</button>
    }
}

<div id="notifications-container">
    @if (Model.Notifications.Count() == 0)
    {
        <h4 class="text-info text-center">Currently you don't have notifications</h4>
    }
    else
    {
        @Html.Partial("_NotificationsPartial", Model.Notifications)
    }
</div>
@if (Model.Notifications.Count() > 19)
{
    using (Ajax.BeginForm("ShowMoreResults", "Notification", new { skip = 20, count = byte.MaxValue, userId = User.Identity.GetUserId() }, new AjaxOptions()
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.InsertAfter,
        UpdateTargetId = "notifications-container",
        OnSuccess = "hideShowMoreLink"
    }, new { id = "showMoreResults", @class = "moreResults" }))
    {
        @Html.AntiForgeryToken()
        <h4 class="text-center">
            <input type="submit" class="btn btn-block" value="Show more" />
        </h4>
    }
}

@section scripts {
    @Scripts.Render("~/Scripts/notifications-view.js")
}

MeetMe/MeetMe.Web/Views/Notification/_NotificationsPartial.cshtml
@using Microsoft.AspNet.Identity
@using MeetMe.Web.Models.Notifications
@model IEnumerable<NotificationUserViewModel>

@foreach (var notification in Model)
{
    <div class="row">
        <div class="col-xs-12 col-sm-offset-3 col-sm-5">
            <div class="panel panel-default panel-google-plus">
                <div class="panel-heading">
                    @using (Ajax.BeginForm("RemoveNotification", "Notification", new { id = notification.Id, userId = User.Identity.GetUserId() }, new AjaxOptions()
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "notifications-container"
                    }, new { @class = "format" }))
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-link pull-right"><i class="glyphicon glyphicon-remove text-danger"></i></button>
                    }
                    <img class="img-circle pull-left notification-img" src="@notification.AuthorImageUrl" alt="Notification image" />
                    <h3>@notification.Author</h3>
                    <h5><span>Shared publicly</span> - <span>@notification.CreatedOn</span> </h5>
                </div>
                <div class="panel-body">
                    <p>@notification.Content</p>
                </div>
                @if (notification.IsFriendship)
                {
                    <div class="panel-footer">
                        @using (Ajax.BeginForm("AcceptFriendship", "Notification", new { id = User.Identity.GetUserId(), notificationId = notification.Id }, new AjaxOptions()
                        {
                            HttpMethod = "POST",
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = "notifications-container"
                        }, new { @class = "format" }))
                        {
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="authorId" value="@notification.AuthorId" />
                            <button type="submit" data-id="@User.Identity.GetUserId()" data-receiverId="@notification.AuthorId" class="btn btn-success btn-accept">Accept</button>
                        }
                        @using (Ajax.BeginForm("RejectFriendship", "Notification", new { id = User.Identity.GetUserId(), authorId = notification.AuthorId, notificationId = notification.Id }, new AjaxOptions()
                        {
                            HttpMethod = "POST",
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = "notifications-container"
                        }, new { @class = "format" }))
                        {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger">Reject</button>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
}